{{- if .Values.externalSecret.enabled }}
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: backend-db-credentials
  namespace: backend-production
  labels:
    {{- include "backend.labels" . | nindent 4 }}
spec:
  refreshInterval: {{ .Values.externalSecret.refreshInterval }}
  secretStoreRef:
    name: {{ .Values.externalSecret.secretStoreName }}
    kind: {{ .Values.externalSecret.secretStoreKind }}
  target:
    name: {{ .Values.externalSecret.targetSecretName }}
    creationPolicy: Owner
  data:
    {{- range .Values.externalSecret.properties }}
    - secretKey: {{ .secretKey }}
      remoteRef:
        key: {{ $.Values.externalSecret.remoteKey }}
        property: {{ .remoteProperty }}
    {{- end }}
{{- end }}
